let lessons = [
    {
        'id': 1,
        'subject': "Math",
        'location': "London",
        'price': 49,
        'Numberofspaces': 5, 
        'image': "images/math.png",
    },
    {
        'id': 2,
        'subject': "English",
        'location': "London",
        'price': 30,
        'Numberofspaces': 5, 
        'image': "images/math.png",
    },
    {
        'id': 3,
        'subject': "Physics",
        'location': "London",
        'price': 75,
        'Numberofspaces': 5, 
        'image': "images/math.png",
    },
    {
        'id': 4,
        'subject': "Chemistry",
        'location': "Kenya",
        'price': 60,
        'Numberofspaces': 5, 
        'image': "images/math.png",
    },
    {
        'id': 5,
        'subject': "Biology",
        'location': "mogotio",
        'price': 20,
        'Numberofspaces': 5, 
        'image': "images/math.png",
    },
    {
        'id': 6,
        'subject': "Biology",
        'location': "mufrin",
        'price': 40,
        'Numberofspaces': 5, 
        'image': "images/math.png",
    },
    {
        'id': 7,
        'subject': "Biology",
        'location': "jikuy",
        'price': 50,
        'Numberofspaces': 5, 
        'image': "images/math.png",
    },
    {
        'id': 5,
        'subject': "Biology",
        'location': "London",
        'price': 40,
        'Numberofspaces': 5, 
        'image': "images/math.png",
    },
    {
        'id': 7,
        'subject': "Biology",
        'location': "ukiuw",
        'price': 40,
        'Numberofspaces': 5, 
        'image': "images/math.png",
    },
    {
        'id': 8,
        'subject': "Biology",
        'location': "we kwenda",
        'price': 10,
        'Numberofspaces': 5, 
        'image': "images/math.png",
    },
    {
        'id': 9,
        'subject': "Biology",
        'location': "its",
        'price': 70,
        'Numberofspaces': 5, 
        'image': "images/math.png",
    },
    {
        'id': 10,
        'subject': "Biology",
        'location': "London",
        'price': 80,
        'Numberofspaces': 5, 
        'image': "images/math.png",
    },
]